backend/authentication-service/Models/ErrorViewModel.cs
namespace authentication_service.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

backend/authentication-service/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace authentication_service.Models
{
    public class LoginViewModel
    {
        [Required]
        public string Login { get; set; }
        [Required]
        public string Password { get; set; }
        public string ReturnUrl { get; set; }
    }
}

backend/authentication-service/Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using authentication_service.Models;
using authentication_service.Storage;
using Duende.IdentityServer.Services;
using Microsoft.AspNetCore.Identity;

namespace authentication_service.Controllers
{
    public class AccessController : Controller
    {
        /*private IAccessService _accessService;
        public AccessController(IAccessService service)
        {
            _accessService = service;
        }*/

        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;
        private readonly IIdentityServerInteractionService _interactionService;

        public AccessController(SignInManager<User> signInManager, UserManager<User> userManager,
            IIdentityServerInteractionService interactionService) =>
            (_signInManager, _userManager, _interactionService) =
            (signInManager, userManager, interactionService);

        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            /*ClaimsPrincipal claimUser = HttpContext.User;

            if (claimUser.Identity.IsAuthenticated)
            {
                if (claimUser.HasClaim(ClaimTypes.Role, "Employee") && !claimUser.HasClaim(ClaimTypes.Role, "Client"))
                {
                    return Redirect("http://localhost:3001");
                }
                else if (!claimUser.HasClaim(ClaimTypes.Role, "Employee") && claimUser.HasClaim(ClaimTypes.Role, "Client"))
                {
                    return Redirect("http://localhost:3000");
                }
                else return View("Selection");
            }*/

            var viewModel = new LoginViewModel
            {
                ReturnUrl = returnUrl
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var user = await _userManager.FindByNameAsync(model.Login);
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "User not found");
                return View(model);
            }

            var result = await _signInManager.PasswordSignInAsync(model.Login,
                model.Password, false, false);
            if (result.Succeeded)
            {
                return Redirect(model.ReturnUrl);
            }
            ModelState.AddModelError(string.Empty, "Login error");
            return View(model);

            /*try
            {
                var identity = _accessService.Login(model);

                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                    IsPersistent = true
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(identity), properties);

                if (identity.HasClaim(ClaimTypes.Role, "Employee") && !identity.HasClaim(ClaimTypes.Role, "Client"))
                {
                    return Redirect("http://localhost:3001");
                }
                else if (!identity.HasClaim(ClaimTypes.Role, "Employee") && identity.HasClaim(ClaimTypes.Role, "Client"))
                {
                    return Redirect("http://localhost:3000");
                }
                else return View("Selection");
            }
            catch (Exception e)
            {
                if (e.Message == "Invalid login or password")
                {
                    return StatusCode(400, "Auth failed: " + e.Message);
                }
                return StatusCode(500, "Something went wrong");
            }*/
        }

        /*[HttpPost]
        [Route("[controller]/[action]")]
        public IActionResult CheckAccess(AccessForRoles model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            Console.WriteLine(User.Identity.Name);
            ClaimsPrincipal claimUser = HttpContext.User;
            if (!claimUser.Identity.IsAuthenticated)
            {
                Console.WriteLine("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
                return Unauthorized();
            }
            var isClient = claimUser.HasClaim(ClaimTypes.Role, "Client");
            var isEmployee = claimUser.HasClaim(ClaimTypes.Role, "Employee");

            if (model.IsForClient == true && model.IsForEmployee == true)
            {
                if (isEmployee == true || isClient == true)
                {
                    return Ok();
                }
                else return Unauthorized();
            }

            else if (model.IsForEmployee == true && model.IsForClient == false)
            {
                if (isEmployee == true)
                {
                    return Ok();
                }
                else return Unauthorized();
            }

            else if (model.IsForEmployee == false && model.IsForClient == true)
            {
                if (isClient == true)
                {
                    return Ok();
                }
                else return Unauthorized();
            }

            else
            {
                return Unauthorized();
            }
        }*/
    }
}

backend/authentication-service/Controllers/AuthController.cs
using authentication_service.Services;
using authentication_service.Storage;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace authentication_service.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AuthController : Controller
    {
        private IAuthService _authService;
        public AuthController(IAuthService service)
        {
            _authService = service;
        }

        [HttpPost]
        [Route("register")]
        public async Task<IActionResult> Register(RegisterDto model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                await _authService.Register(model);
                return Ok();
            }
            catch (Exception ex)
            {
                if (ex.Message == "A user with the same login already exists")
                {
                    return StatusCode(400, "Registration failed: " + ex.Message);
                }
                return StatusCode(500, "Something went wrong");
            }
        }
    }
}

backend/authentication-service/Controllers/HomeController.cs
using authentication_service.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace authentication_service.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

backend/authentication-service/Views/Access/Login.cshtml
@model authentication_service.Models.LoginViewModel;
@{
	ViewData["Title"] = "Login";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

<div class="container">
    <div class="row justify-content-start">
        <div class="col-md-6 offset-md-3">
            <form asp-controller="Access" asp-action="Login" method="post">
                <input type="hidden" asp-for="ReturnUrl" />
                <div class="mb-3">
                    <label for="InputLogin" class="form-label">Login</label>
                    <input type="text" class="form-control" id="InputLogin" asp-for="Login">
                </div>
                <div class="mb-3">
                    <label for="InputPassword" class="form-label">Password</label>
                    <input type="password" class="form-control" id="InputPassword" asp-for="Password">
                </div>
                <button type="submit" class="btn btn-primary">Enter</button>
            </form>
        </div>
    </div>
</div>

backend/authentication-service/Views/Access/Selection.cshtml
@{
	ViewData["Title"] = "Selection";
}

<div class="container">
    <div class="row justify-content-start">
        <div class="col-md-6 offset-md-3">
            <button type="button" class="btn btn-light"><a href="http://localhost:3000">Client</a></button>
            <button type="button" class="btn btn-light"><a href="http://localhost:3001">Employee</a></button>
        </div>
    </div>
</div>

backend/authentication-service/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - online-bank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/authentication_service.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Access" asp-action="Login">online-bank</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            &copy; 2023 - online-bank
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>